name: dotNET REST API

services:
  project-database:
    container_name: BookDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - ./Book-DB/data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Pwd1234!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped