// <auto-generated />
using System;
using Book_App_API.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_App_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250210123434_SeedBookAndJunctionTables")]
    partial class SeedBookAndJunctionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_App_API.Domain.Entity.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Roderick",
                            Surname = "Gordon"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Brian",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Joanne",
                            Surname = "Rowling"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "George",
                            Surname = "Orwell"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Jane",
                            Surname = "Austen"
                        },
                        new
                        {
                            Id = 6,
                            Firstname = "Mark",
                            Surname = "Twain"
                        },
                        new
                        {
                            Id = 7,
                            Firstname = "F. Scott",
                            Surname = "Fitzgerald"
                        },
                        new
                        {
                            Id = 8,
                            Firstname = "Ernest",
                            Surname = "Hemingway"
                        },
                        new
                        {
                            Id = 9,
                            Firstname = "Harper",
                            Surname = "Lee"
                        },
                        new
                        {
                            Id = 10,
                            Firstname = "Isaac",
                            Surname = "Asimov"
                        },
                        new
                        {
                            Id = 11,
                            Firstname = "Brandon",
                            Surname = "Sanderson"
                        },
                        new
                        {
                            Id = 12,
                            Firstname = "Carlos",
                            Surname = "Ruiz Zafón"
                        });
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReaderAgeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReaderAgeId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Pages = 464,
                            PublishDate = new DateTime(2007, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 5,
                            Title = "Tunnels"
                        },
                        new
                        {
                            Id = 2,
                            Pages = 655,
                            PublishDate = new DateTime(2009, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 5,
                            Title = "Deeper"
                        },
                        new
                        {
                            Id = 3,
                            Pages = 577,
                            PublishDate = new DateTime(2009, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 5,
                            Title = "Freefall"
                        },
                        new
                        {
                            Id = 4,
                            Pages = 508,
                            PublishDate = new DateTime(2010, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 5,
                            Title = "Closer"
                        },
                        new
                        {
                            Id = 5,
                            Pages = 443,
                            PublishDate = new DateTime(2011, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 5,
                            Title = "Spiral"
                        },
                        new
                        {
                            Id = 6,
                            Pages = 402,
                            PublishDate = new DateTime(2013, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 5,
                            Title = "Terminal"
                        },
                        new
                        {
                            Id = 7,
                            Pages = 328,
                            PublishDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 6,
                            Title = "Nineteen Eighty-Four"
                        },
                        new
                        {
                            Id = 8,
                            Pages = 253,
                            PublishDate = new DateTime(1950, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReaderAgeId = 6,
                            Title = "I, Robot"
                        });
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.BookAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthor");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 1,
                            Id = 1
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 1,
                            Id = 2
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 2,
                            Id = 3
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 2,
                            Id = 4
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 3,
                            Id = 5
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 3,
                            Id = 6
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 4,
                            Id = 7
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 4,
                            Id = 8
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 5,
                            Id = 9
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 5,
                            Id = 10
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 6,
                            Id = 11
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 6,
                            Id = 12
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 7,
                            Id = 13
                        },
                        new
                        {
                            AuthorId = 10,
                            BookId = 8,
                            Id = 14
                        });
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.BookGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            BookId = 1,
                            Id = 1
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 1,
                            Id = 2
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 2,
                            Id = 3
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 2,
                            Id = 4
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 3,
                            Id = 5
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 3,
                            Id = 6
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 4,
                            Id = 7
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 4,
                            Id = 8
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 5,
                            Id = 9
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 5,
                            Id = 10
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 6,
                            Id = 11
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 6,
                            Id = 12
                        },
                        new
                        {
                            GenreId = 3,
                            BookId = 7,
                            Id = 13
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 7,
                            Id = 14
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 8,
                            Id = 15
                        });
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Dystopian"
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Action & Adventure"
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            GenreName = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            GenreName = "Romance"
                        });
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.ReaderAge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReaderAges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRange = "Picture Books (Ages 0-5)"
                        },
                        new
                        {
                            Id = 2,
                            AgeRange = "Early Readers (Ages 5-7)"
                        },
                        new
                        {
                            Id = 3,
                            AgeRange = "Chapter Books (Ages 7-9)"
                        },
                        new
                        {
                            Id = 4,
                            AgeRange = "Middle Grade (Ages 8-12)"
                        },
                        new
                        {
                            Id = 5,
                            AgeRange = "Young Adult (YA) (Ages 12-18)"
                        },
                        new
                        {
                            Id = 6,
                            AgeRange = "Adult (Ages 18+)"
                        });
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.Book", b =>
                {
                    b.HasOne("Book_App_API.Domain.Entity.ReaderAge", "ReaderAge")
                        .WithMany()
                        .HasForeignKey("ReaderAgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReaderAge");
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.BookAuthor", b =>
                {
                    b.HasOne("Book_App_API.Domain.Entity.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book_App_API.Domain.Entity.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.BookGenre", b =>
                {
                    b.HasOne("Book_App_API.Domain.Entity.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book_App_API.Domain.Entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Book_App_API.Domain.Entity.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
